### ISSUE TITLE
Id is default value is "0" in created model 

### ISSUE THREAD

**Issue by Alireza-Milani** [infinum/kotlin-jsonapix#20] opened 2022-06-07 06:36 UTC
Hi there

I think when your library convert json string to model with toResourceObject function, id in json string doesn't set in model and default value sets in this model

**Comment by stjepanbanek** [comment] 2022-06-29 09:33
Hi, thanks for your feedback.
At this moment the default value for id being `"0"` is intended behaviour for the serialization process.
We are planning to add support to get/set the `id` value through the `JsonApiModel` class.

Let me try to explain why the current behaviour is intended though:

1. `id` is a required entry in the JSON:API specification
2. The responsibility of setting an `id` rests on the server, not the client. 
3. Therefore, the client uses the default value of `"0"` in serialization, just to account for the specification requirements.  
4. The server should be responsible for overwriting the default value  with an actual id

Hope this helps. Anyway, we do plan to introduce some is modifying options to the lib, even though it should be only done on the server side.

**Comment by Alireza-Milani** [comment] 2022-06-29 10:13
Your response is true. But when id is defined in server API, in library server id value doesn't map into this id property in toResourceObject.
 
I think id is a required for list items that must are shown in recyclerView or other widgets that handle list

**Comment by stjepanbanek** [comment] 2022-06-29 10:16
Ok, I get your point better now. Feel free to open a pull request if you want, and I will review the changes to see if it can be merged. Regardless of that, I will look into the issue as soon as I can.

**Comment by stjepanbanek** [comment] 2022-07-04 09:02
Use this [PR](https://github.com/infinum/kotlin-jsonapix/pull/22) as a reference to fixing this issue

**Closed** 2022-10-12 12:09 UTC
Labels: bug
