### ISSUE TITLE
I cannot find TypeAdapterFactory

### ISSUE THREAD

**Issue by GuiOliveira-Git** [infinum/kotlin-jsonapix#53] opened 2023-06-20 22:33 UTC
I am trying to build Retrofit:
```
internal fun provideRetrofit(okHttpClient: OkHttpClient): Retrofit {
    val gson = GsonBuilder().setLenient().create()

    return Retrofit.Builder()
        .baseUrl(BuildConfig.MILLENNIUM_BASE_URL)
        .addConverterFactory(GsonConverterFactory.create(gson))
        .addConverterFactory(JsonXConverterFactory(TypeAdapterFactory()))
        .client(okHttpClient)
        .build()
}
```

I am not able to import com.infinum.jsonapix.TypeAdapterFactory. Any clue why it's happening?

**Comment by thisAAY** [comment] 2023-10-05 14:47
Can you share with us your Gradle files?

**Comment by thisAAY** [comment] 2023-10-30 16:28
This could be a duplicate of  #55

**Closed** 2024-01-30 15:58 UTC
Labels: duplicate
